- name: Install helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install helm chart
  kubernetes.core.helm:
    name: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    chart_ref: jetstack/cert-manager
    values: 
      installCRDs: true

- name: Set ClusterIssuer
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: "{{ email }}"
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - http01:
                ingress:
                  class: nginx