- name: Get an existing Service object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: redis
  register: ns

- block:
    - name: Install helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Install helm chart
      kubernetes.core.helm:
        name: redis
        release_namespace: redis
        create_namespace: true
        update_repo_cache: true
        chart_ref: bitnami/redis-cluster
        values: 
          password: "vagrant"
          persistence:
            storageClass: "cstor-csi-disk"
            size: 2Gi
  when: (ns is not defined) or (ns == None) or (ns.resources | length == 0)
