- name: Install Helm diff plugin
  become_user: vagrant
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Copy kubectl config
  fetch:
    src: /home/vagrant/.kube/config
    dest: ~/.kube/
    flat: true

- name: Install python libraries
  pip: 
    name: [psycopg2-binary]
    state: present
