- name: Install helm repo
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"

- name: Install nfs provisioner
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    release_namespace: nfsstorage
    create_namespace: true
    update_repo_cache: true
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    values:
      nfs:
        server: 192.167.56.1
        path: /opt/k8s_nfs_storage
