- name: Install apt packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"

- name: Create zpool
  shell:  "zpool create iscsi raidz1 /dev/vdb /dev/vdc /dev/vdd /dev/vde /dev/vdf /dev/vdg"

- name: Create ZFS targets
  set_fact:
    zfs_targets: "{{ zfs_targets | default([]) + [{'name': 'volume' + (tgt_id + 1) | string, 'lun': 'iqn.' + ansible_date_time.year + '-' + ansible_date_time.month + '.' + domain + ':lun' + (tgt_id + 1) | string , 'initiator': hostvars[item].ansible_host}] }}"
  loop: '{{ groups["k8s_nodes"] }}'
  loop_control:
    index_var: tgt_id

- name: Create ZFS volume
  shell: "zfs create -V 144G iscsi/{{ item.name }}"
  with_items: "{{ zfs_targets }}"

- name: Configure iscsi target
  template:
    src: targets.conf.j2
    dest: /etc/tgt/targets.conf

- name: Start iscsi target
  systemd:
    name: tgt
    state: restarted
    enabled: true